
-- create
CREATE TABLE GROUPMATES (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  adress TEXT NOT NULL
);

-- insert
INSERT INTO GROUPMATES VALUES (0001, 'Clark', 20,'Turan 59');
INSERT INTO GROUPMATES VALUES (0002, 'Dave',22,'Mangilik-el 42A');
INSERT INTO GROUPMATES VALUES (0003, 'Ava', 19,'Uly-Dala 8');
INSERT INTO GROUPMATES VALUES (0004, 'Carl', 23,'Moscow');
INSERT INTO GROUPMATES VALUES (0005, 'Abay', 20,'Moscow');
INSERT INTO GROUPMATES VALUES (0006, 'Salauat', 19,'Uly-Dala 12');
INSERT INTO GROUPMATES VALUES (0007, 'Tamerlan', 22,'Turan 44');

-- fetch 
SELECT name FROM GROUPMATES WHERE adress = 'Moscow' and age > 18. and age < 30;
